version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  rabbitmq:
    image: rabbitmq:3.9.7
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
volumes:
  mongodb_data:
