swagger: "2.0"
info:
  version: "1.0.0"
  title: "API de Usuários"
  description: "API para gerenciar usuários"
basePath: "/api"
schemes:
  - "http"
paths:
  /users:
    get:
      summary: "Listar todos os usuários"
      responses:
        200:
          description: "Lista de todos os usuários"
    post:
      summary: "Adicionar um novo usuário"
      parameters:
        - in: "body"
          name: "body"
          description: "Objeto contendo informações do novo usuário"
          required: true
          schema:
            type: "object"
            properties:
              name:
                type: "string"
              email:
                type: "string"
          example:
            name: "Felipe"
            email: "felipe@lumx.com"
      responses:
        200:
          description: "Usuário adicionado com sucesso"
        400:
          description: "Erro: Parâmetros inválidos"
    put:
      summary: "Atualizar um usuário existente"
      parameters:
        - in: "body"
          name: "body"
          description: "Objeto contendo informações do usuário a ser atualizado"
          required: true
          schema:
            type: "object"
            properties:
              name:
                type: "string"
              email:
                type: "string"
          example:
            name: "Felipe"
            email: "felipe@lumx.com"
      responses:
        200:
          description: "Usuário atualizado com sucesso"
        400:
          description: "Erro: Parâmetros inválidos ou Usuário a ser atualizado não existe"
  /users/{email}:
    get:
      summary: "Obter um usuário pelo email"
      parameters:
        - name: "email"
          in: "path"
          description: "Email do usuário a ser obtido"
          required: true
          type: "string"
      responses:
        200:
          description: "Usuário encontrado"
        400:
          description: "Erro: Usuário não encontrado"
    delete:
      summary: "Remover um usuário pelo email"
      parameters:
        - name: "email"
          in: "path"
          description: "Email do usuário a ser removido"
          required: true
          type: "string"
      responses:
        200:
          description: "Usuário removido com sucesso"
        400:
          description: "Erro: Parâmetros inválidos ou Usuário a ser removido não existe"
